# -*- coding: utf-8 -*-
"""02_multihop_full_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSFT2t9yLq_Jauj9RE3OUN9EKTGJI-j4

# MultiHop-RAG — Full Pipeline: Retrieval, Generation, RAGAS Evaluation
**Project:** Evaluating the Reliability of Selected RAG Evaluation Metrics for Finance-Related QA
**Student:** Ayusha Shrestha

Confirmed from Notebook 5:
- `corpus` has 609 full articles (`body`, `title`, `source`, `category`, `published_at`, `author`, `url`)
- 3 usable question types: `comparison_query` (856), `inference_query` (816), `temporal_query` (583)
- `null_query` (301, all with empty evidence) is set aside — these test whether a system
  correctly abstains rather than testing retrieval/faithfulness, a different question from
  the rest of this analysis. Worth a short separate mention in the report, not mixed into
  the main comparison.

**Sampling:** stratified — 5 rows from each of the 3 usable question types (n=15 total,
matching `finqa`'s sample size). Stratified rather than plain random so every question
type is guaranteed representation, which plain random sampling at n=15 could easily miss
for the smaller `temporal_query` category. This is a deliberate methodological choice
worth stating explicitly in the report.

**What's new here that `finqa` did not need:**
1. A retrieval step — embed the corpus, find the most relevant articles per query
2. A generation step — Groq (Llama 3.1) produces the actual response RAGAS evaluates
3. Reference-based Context Precision (not the reference-free variant) — because MultiHop-RAG
   provides a genuine gold `answer` to use as ground truth, unlike `finqa`

## 1. Install a compatible, pinned set of libraries
Same pinned stack as before, plus `faiss-cpu` for retrieval.
"""

!pip install -q \
  "ragas==0.2.15" \
  "langchain==0.3.27" "langchain-core==0.3.76" "langchain-community==0.3.30" \
  "langchain-openai==0.2.14" "langchain-groq==0.2.4" "langchain-huggingface==0.1.2" \
  datasets sentence-transformers faiss-cpu

print("Libraries installed.")

"""## 2. Add your API keys"""

import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("Paste your Groq API key here: ")
print("Groq key stored for this session.")

from huggingface_hub import login

login(getpass("Paste your Hugging Face token here: "))

"""## 3. Load both subsets and take a stratified sample"""

from datasets import load_dataset
import pandas as pd

queries_dataset = load_dataset("yixuantt/MultiHopRAG", "MultiHopRAG")
corpus_dataset = load_dataset("yixuantt/MultiHopRAG", "corpus")

df_queries = queries_dataset["train"].to_pandas()
df_corpus = corpus_dataset["train"].to_pandas()

# Exclude null_query rows (no evidence, tests abstention, different question)
df_usable = df_queries[df_queries["question_type"] != "null_query"].reset_index(drop=True)

# Stratified sample: 5 rows per question type.
# Built with a simple loop + concat rather than groupby().apply() -- in some pandas
# versions, groupby().apply() silently drops the grouping column from the result,
# which would lose question_type entirely. This approach avoids that.
ROWS_PER_TYPE = 5
samples = []
for qtype in df_usable["question_type"].unique():
    subset = df_usable[df_usable["question_type"] == qtype]
    samples.append(subset.sample(n=ROWS_PER_TYPE, random_state=42))

df_sample = pd.concat(samples).reset_index(drop=True)

print("Sample shape:", df_sample.shape)
print(df_sample["question_type"].value_counts())

"""## 4. Build the retrieval index

Embed all 609 corpus articles once, using the same local, free embedding model used
throughout this project. Article bodies can be long (some include scraped boilerplate,
e.g. "Table of Contents" navigation text seen in Notebook 5) — the embedding model
handles this by focusing on the earlier part of the text, a normal and accepted
limitation of this kind of embedding, worth a one-line mention in the methodology.

"""

from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

embed_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

corpus_texts = df_corpus["body"].tolist()
corpus_embeddings = embed_model.encode(corpus_texts, show_progress_bar=True, convert_to_numpy=True)

# Normalize for cosine similarity via inner product
faiss.normalize_L2(corpus_embeddings)

index = faiss.IndexFlatIP(corpus_embeddings.shape[1])
index.add(corpus_embeddings)

print(f"Indexed {index.ntotal} articles.")

"""## 5. Retrieve the top-k most relevant articles per query

Using k=3, matching MultiHop-RAG's own design (evidence is drawn from 2-4 documents
per query, so 3 is a reasonable middle value).

"""

import textwrap

TOP_K = 3
MAX_CONTEXT_CHARS = 1200  # truncate each retrieved article to keep prompts within Groq's free-tier token budget
WRAP_WIDTH = 80

def retrieve_contexts(query, top_k=TOP_K):
    query_embedding = embed_model.encode([query], convert_to_numpy=True)
    faiss.normalize_L2(query_embedding)
    scores, indices = index.search(query_embedding, top_k)
    retrieved = []
    for idx in indices[0]:
        body = df_corpus.iloc[idx]["body"]
        retrieved.append(body[:MAX_CONTEXT_CHARS])
    return retrieved

df_sample["retrieved_contexts"] = df_sample["query"].apply(retrieve_contexts)

# Quick sanity check on one row
print("Example query:")
print(textwrap.fill(df_sample.iloc[0]["query"], WRAP_WIDTH))
print()
print("Retrieved contexts (truncated):")
for i, ctx in enumerate(df_sample.iloc[0]["retrieved_contexts"]):
    print(f"[{i}]")
    print(textwrap.fill(ctx[:200] + "...", WRAP_WIDTH))
    print()

"""## 6. Generate an answer for each query using Groq

This is the "response" RAGAS will evaluate — analogous to `finqa`'s pre-existing
`response` column, except here we produce it ourselves from the retrieved context.

"""

from langchain_groq import ChatGroq
import time

generator_llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)

def generate_response(query, contexts):
    context_block = "\n\n".join(f"Source {i+1}: {c}" for i, c in enumerate(contexts))
    prompt = (
        f"Answer the question using only the information in the sources below. "
        f"Be concise and direct.\n\n{context_block}\n\nQuestion: {query}\nAnswer:"
    )
    result = generator_llm.invoke(prompt)
    return result.content

responses = []
for idx, row in df_sample.iterrows():
    print(f"Generating response {idx + 1}/{len(df_sample)}...")
    response = generate_response(row["query"], row["retrieved_contexts"])
    responses.append(response)
    time.sleep(2)  # small pause to stay well within Groq's free-tier rate limits

df_sample["response"] = responses
print()
print("Done. Example:")
print("Q:", df_sample.iloc[0]["query"])
print("A:", df_sample.iloc[0]["response"])
print("Gold answer:", df_sample.iloc[0]["answer"])

"""## 7. Set up the LLM judge and run RAGAS

Same judge setup as `finqa` (Groq/Llama 3.1), but using the **standard, reference-based
Context Precision** this time, since we have a genuine gold `answer` to compare against.

"""

from ragas import evaluate, EvaluationDataset
from ragas.metrics import faithfulness, answer_relevancy, context_precision
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_huggingface import HuggingFaceEmbeddings
from ragas.run_config import RunConfig

judge_llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
ragas_llm = LangchainLLMWrapper(judge_llm)

embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
ragas_embeddings = LangchainEmbeddingsWrapper(embedding_model)

ragas_rows = []
for _, row in df_sample.iterrows():
    ragas_rows.append({
        "user_input": row["query"],
        "response": row["response"],
        "retrieved_contexts": row["retrieved_contexts"],
        "reference": row["answer"],
    })

eval_dataset = EvaluationDataset.from_list(ragas_rows)

slow_and_steady = RunConfig(
    timeout=300,
    max_workers=2,
    max_retries=15,
    max_wait=90,
)

results = evaluate(
    dataset=eval_dataset,
    metrics=[faithfulness, answer_relevancy, context_precision],
    llm=ragas_llm,
    embeddings=ragas_embeddings,
    run_config=slow_and_steady,
)

results_df = results.to_pandas()
results_df

"""## 8. Check for and retry any failed rows

Same approach as `finqa` — free-tier timeouts are normal, not a broken pipeline.
"""

metric_cols = ["faithfulness", "answer_relevancy", "context_precision"]

missing_counts = results_df[metric_cols].isna().sum()
print("Missing values per metric:")
print(missing_counts)

failed_mask = results_df[metric_cols].isna().any(axis=1)
failed_indices = results_df[failed_mask].index.tolist()

print(f"Retrying {len(failed_indices)} row(s): {failed_indices}")

if len(failed_indices) > 0:
    retry_rows = [ragas_rows[i] for i in failed_indices]
    retry_dataset = EvaluationDataset.from_list(retry_rows)

    retry_results = evaluate(
        dataset=retry_dataset,
        metrics=[faithfulness, answer_relevancy, context_precision],
        llm=ragas_llm,
        embeddings=ragas_embeddings,
        run_config=slow_and_steady,
    )
    retry_df = retry_results.to_pandas()

    for pos, orig_idx in enumerate(failed_indices):
        for col in metric_cols:
            if pd.isna(results_df.loc[orig_idx, col]):
                results_df.loc[orig_idx, col] = retry_df.loc[pos, col]

    print("Retry complete. Remaining missing values:")
    print(results_df[metric_cols].isna().sum())
else:
    print("No missing values - nothing to retry.")

"""## 9. Build the final results table and save it"""

comparison_df = pd.concat([
    df_sample[["query", "question_type", "answer", "response"]].reset_index(drop=True),
    results_df[metric_cols].reset_index(drop=True)
], axis=1)

comparison_df.to_csv("multihop_rag_final_results.csv", index=False)
print("Saved: multihop_rag_final_results.csv")
comparison_df

"""## 10. Compare average scores by (native) question type

Using MultiHop-RAG's own ground-truth question types, not a heuristic tagger.

"""

print("Average scores by question type:")
print(comparison_df.groupby("question_type")[metric_cols].mean().round(3))
print()
print("Row counts per group:")
print(comparison_df["question_type"].value_counts())

import pandas as pd
import textwrap

pd.set_option('display.max_colwidth', 60)

df = pd.read_csv("multihop_rag_final_results.csv")

WRAP_WIDTH = 80

# ---------- TABLE 3: terse-but-correct answers ----------
print("=" * WRAP_WIDTH)
print("Terse-but-correct answers")
print("=" * WRAP_WIDTH)

table3_targets = ["Google.", "Amazon.", "The country is Israel."]
table3 = df[df["response"].isin(table3_targets)][
    ["response", "answer", "answer_relevancy"]
].reset_index(drop=True)
table3.columns = ["Response", "Gold Answer", "Answer Relevancy"]
table3["Answer Relevancy"] = table3["Answer Relevancy"].round(3)

print(table3.to_string(index=False))
print()

pd.set_option('display.max_colwidth', 60)
df = pd.read_csv("multihop_rag_final_results.csv")

WRAP_WIDTH = 80

print("=" * WRAP_WIDTH)
print("Confidently wrong answer scoring perfectly")
print("=" * WRAP_WIDTH)

table4_row = df[df["response"].str.contains("GPT-4", na=False)].iloc[0]

print("QUERY:")
print(textwrap.fill(table4_row["query"], WRAP_WIDTH))
print()
print("RESPONSE:")
print(textwrap.fill(table4_row["response"], WRAP_WIDTH))
print()

table4_summary = pd.DataFrame([{
    "Gold Answer": table4_row["answer"],
    "Faithfulness": round(table4_row["faithfulness"], 3),
    "Context Precision": round(table4_row["context_precision"], 3),
}])
print(table4_summary.to_string(index=False))

"""## Progress Note — RAGAS Metric Recomputation on MultiHop-RAG

Built a retrieval-augmented pipeline from scratch for MultiHop-RAG, since (unlike RAGBench) it provides no pre-generated response: embedded all 609 corpus articles using sentence-transformers, built a FAISS index, retrieved the top-3 most relevant articles per query, and generated an answer for each using Groq (Llama 3.1). Sample was stratified (5 rows each) across MultiHop-RAG's three usable native question types — comparison_query, inference_query, temporal_query — with null_query (301 rows, all lacking supporting evidence) set aside as a separate abstention-testing case rather than mixed into the main analysis. Used RAGAS's standard, reference-based Context Precision this time, since MultiHop-RAG (unlike finqa) provides a genuine gold answer.

**Result**: Successfully scored all 15 rows across all three metrics (2 initial timeouts resolved via retry).
"""